# Generated by Django 5.2 on 2025-05-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication_tracker', '0002_sideeffect'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='category',
            field=models.CharField(choices=[('joints', 'Joints and Muscles'), ('gut', 'Gut Health'), ('skin', 'Skin'), ('ent', 'Eyes-Ears-Nose-Throat'), ('neuro', 'Headaches and Dizziness'), ('cardio', 'Heart Health')], default='other', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='category',
            field=models.CharField(choices=[('nausea', 'Nausea or Vomiting'), ('fatigue', 'Fatigue or Weakness'), ('rash', 'Rashes or Skin Issues'), ('mood', 'Mood Changes'), ('pain', 'Muscle or Joint Pain'), ('cardio', 'Heart Palpitations or Chest Pain')], default='other', max_length=20),
            preserve_default=False,
        ),
    ]
