# Generated by Django 5.2 on 2025-05-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication_tracker', '0003_medication_category_sideeffect_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='category',
            field=models.CharField(choices=[('Joints', 'Joints and Muscles'), ('Gut', 'Gut Health'), ('Skin', 'Skin'), ('Sensory', 'Eyes-Ears-Nose-Throat'), ('Neuro', 'Headaches and Dizziness'), ('Cardio', 'Heart Health')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='category',
            field=models.CharField(choices=[('Nausea', 'Nausea or Vomiting'), ('Fatigue', 'Fatigue or Weakness'), ('Rash', 'Rashes or Skin Issues'), ('Mood', 'Mood Changes'), ('Pain', 'Muscle or Joint Pain'), ('Cardio', 'Heart Palpitations or Chest Pain')], max_length=20),
        ),
    ]
