# Generated by Django 5.2 on 2025-05-15 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
