# Generated by Django 5.2 on 2025-04-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_4_medication_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['-created_on']},
        ),
    ]
